# This will run on the container-based infrastructure.
sudo: false

# White list.
branches:
  only:
    - master

# libclang-common-3.6-dev is necessary for doxygen in the xenial distribution
# to use clang-assisted parsing.  See dist below.
addons:
  apt:
    packages:
      - doxygen
      - doxygen-latex
      - doxygen-gui
      - graphviz
      - kcov
      - libclang-common-3.6-dev
      - python-pygments
      - python3-pygments

language: cpp

# libclang-common-3.6-dev is necessary for doxygen in the xenial distribution
# to use clang-assisted parsing.  See addons above.
dist: xenial

# 'clang' and 'gcc' are options, but the gcc shipped with the xenial
# distribution does not support a constexpr function that throws.  See dist
# above.
compiler:
  - clang

os:
  - linux

# Build and run unit tests.
script:
  - make test

# Generate doxygen documentation.
#
# It seems that travis's deployment to the gh-pages branch is done in a cool
# way that does not store history there.
#
# - A side-effect is that any attempt manually to push a '.nojekyll' file to
#   the root of the filesystem on the gh-pages branch ends up producing
#   divergent branches and not working.
#
# - So the '.nojekyll' file needs to be written here.
#
# - I'm not sure where it needs to go, and so I put it both under html and at
#   the root.
#
# - I need a '.nojekyll' file because one of the files documented by doxygen is
#   '.ycm_extra_conf.py' on the master branch.
#
# - Apparently because its name begins with '.', doxygen generates a file whose
#   name begins with '_', but jekyll does not allow the copying of such a file
#   over to gh-pages.
after_success:
  - kcov --exclude-path=/usr/include,./test . ./test/tests
  - bash <(curl -s https://codecov.io/bash)
  - doxygen Doxyfile
  - touch html/.nojekyll
  - touch .nojekyll

# Push doxygen documentation to gh-pages.
deploy:
  provider: pages
  skip_cleanup: true
  local-dir: html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
