# This will run on the continer-based infrastructure.
sudo: false

# White list.
branches:
  only:
    - master

# Install dependencies.
addons:
  apt:
    packages:
      - doxygen
      - doxygen-latex
      - graphviz
      - libclang-common-3.6-dev

language: cpp

dist: xenial

compiler:
  - clang

os:
  - linux

script:
  - make test

after_success:
  - doxygen Doxyfile

deploy:
  provider: pages
  skip_cleanup: true
  local-dir: html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
