# This will run on the container-based infrastructure.
sudo: false

# White list.
branches:
  only:
    - master

# libclang-common-3.6-dev is necessary for doxygen in the xenial distribution
# to use clang-assisted parsing.  See dist below.
addons:
  apt:
    packages:
      - doxygen
      - doxygen-latex
      - graphviz
      - libclang-common-3.6-dev

language: cpp

# libclang-common-3.6-dev is necessary for doxygen in the xenial distribution
# to use clang-assisted parsing.  See addons above.
dist: xenial

# 'clang' and 'gcc' are options, but the gcc shipped with the xenial
# distribution does not support a constexpr function that throws.  See dist
# above.
compiler:
  - clang

os:
  - linux

# Build and run unit tests.
script:
  - make test

# Generate doxygen documentation.
after_success:
  - doxygen Doxyfile
  - touch html/.nojekyll
  - touch .nojekyll

# Push doxygen documentation to gh-pages.
deploy:
  provider: pages
  skip_cleanup: true
  local-dir: html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
